version: 2
jobs:
    build:
        docker:
            - image: 'node:8.6.0'
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                key: 'yarn-cache-{{ checksum "yarn.lock" }}'
            - run: yarn install --no-progress
            - save_cache:
                key: 'yarn-cache-{{ checksum "yarn.lock" }}'
                paths:
                    - node_modules
            - run: yarn add coveralls && cat ./coverage/lcov.info | coveralls
            - run: yarn lint
            - run: yarn test 
notify:
    webhooks:
        - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN